2025-01-08 19:13:06,300 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Configure stats pid to 1647138
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Loading settings from /home/sfchan/.config/wandb/settings
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Loading settings from /hdda/models/my_own_models/architectural_and_learning_on_loss_landscape/outputs/2025-01-08/19-13-02/wandb/settings
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'experiments/basic_training/single_loss_gradient_expr.py', 'program_abspath': '/hdda/models/my_own_models/architectural_and_learning_on_loss_landscape/experiments/basic_training/single_loss_gradient_expr.py', 'program': '/hdda/models/my_own_models/architectural_and_learning_on_loss_landscape/experiments/basic_training/single_loss_gradient_expr.py'}
2025-01-08 19:13:06,301 INFO    MainThread:1647138 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-01-08 19:13:06,302 INFO    MainThread:1647138 [wandb_init.py:_log_setup():534] Logging user logs to /hdda/models/my_own_models/architectural_and_learning_on_loss_landscape/outputs/2025-01-08/19-13-02/wandb/run-20250108_191306-n03c79au/logs/debug.log
2025-01-08 19:13:06,302 INFO    MainThread:1647138 [wandb_init.py:_log_setup():535] Logging internal logs to /hdda/models/my_own_models/architectural_and_learning_on_loss_landscape/outputs/2025-01-08/19-13-02/wandb/run-20250108_191306-n03c79au/logs/debug-internal.log
2025-01-08 19:13:06,302 INFO    MainThread:1647138 [wandb_init.py:init():621] calling init triggers
2025-01-08 19:13:06,303 INFO    MainThread:1647138 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key=None, flags={'struct': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {'now': {('%Y-%m-%d',): '2025-01-08', ('%H-%M-%S',): '19-13-02'}}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'struct': True}, '_content': {'use_wandb': True, 'runs': 1, 'seed': 42, 'device': 'cuda', 'epochs': 10, 'data': {'dataset': 'cifar10', 'data_path': None, 'num_classes': 10}, 'net': {'type': 'ConvNet', 'netparams': {'num_classes': '${data.num_classes}'}}, 'learner': {'type': 'backprop', 'device': '${device}', 'opt': 'adam', 'loss': 'nll', 'step_size': 0.01, 'beta_1': 0.95, 'beta_2': 0.999, 'weight_decay': 0.01, 'to_perturb': False, 'perturb_scale': 0.05, 'momentum': 0.9}, 'evaluation': {'eval_freq_epoch': 1, 'eval_metrics': ['accuracy', 'loss'], 'save_dir': '/results/results_raw'}}}
2025-01-08 19:13:06,303 INFO    MainThread:1647138 [wandb_init.py:init():671] starting backend
2025-01-08 19:13:06,303 INFO    MainThread:1647138 [wandb_init.py:init():675] sending inform_init request
2025-01-08 19:13:06,312 INFO    MainThread:1647138 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-08 19:13:06,314 INFO    MainThread:1647138 [wandb_init.py:init():688] backend started and connected
2025-01-08 19:13:06,320 ERROR   MainThread:1647138 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 693, in init
    run = Run(
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 599, in __init__
    self._init(
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 719, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/site-packages/wandb/util.py", line 674, in json_friendly_val
    converted = asdict(val)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/dataclasses.py", line 1075, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/dataclasses.py", line 1082, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/sfchan/anaconda3/envs/loss_landscape/lib/python3.9/dataclasses.py", line 1112, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
